const ROLE = {
  ADMIN: "Admin",
  CASEWORKER: "Caseworker",
  CANDIDATE: "Candidate",
  SPONSOR: "Sponsor"
};

const CASE_STATUS = {
  NEW: "NEW",
  IN_PROGRESS: "IN_PROGRESS",
  PENDING_DOCUMENTS: "PENDING_DOCUMENTS",
  DECISION_PENDING: "DECISION_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CLOSED: "CLOSED",
  ESCALATED: "ESCALATED"
};

module.exports = { ROLE, CASE_STATUS };
